## Basics
<hr style="height:2px;border-width:0;color:black;background-color:black">
One of the most commonly used functions of NumPy are <i>NumPy arrays</i>: The essential difference between <i>lists</i> and <i>NumPy arrays</i> is functionality and speed. <i>lists</i> give you basic operation, but <i>NumPy</i> adds FFTs, convolutions, fast searching, basic statistics, linear algebra, histograms, etc.</br>
The most important difference for data science is the ability to do <b>element-wise calculations</b> with <i>NumPy arrays</i>

| Operator     | Description   | Documentation |
| :------------- | :------------- | :--------|
|`np.array([1,2,3])`|1d array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array)|
|`np.array([(1,2,3),(4,5,6)])`|2d array|see above|
|`np.arange(start,stop,step)`|range array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)|

In [15]:
print(np.array([1,2,3]))
print(np.array([(1,2,3),(4,5,6)]))
print(np.arange(0,10,1))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8 9]


### Placeholders <a name="place"></a>
| Operators | Description |Documentation|
| :------------- | :------------- |:---------- |
|`np.linspace(0,2,9)`|Add evenly spaced values btw interval to array of length |[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)|
|`np.zeros((1,2))`|Create and array filled with zeros|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)|
|`np.ones((1,2))`|Creates an array filled with ones|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)|
|`np.random.random((5,5))`|Creates random array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html)|
|`np.empty((2,2))`|Creates an empty array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html)|


In [20]:
print(np.linspace(0,1,5))
print(np.zeros((1,2)))
print(np.ones((2,2)))
print(np.random.random((3,3)))
print(np.empty((2,2)))

[0.   0.25 0.5  0.75 1.  ]
[[0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.29725444 0.46148047 0.9638985 ]
 [0.94691582 0.37075962 0.5898213 ]
 [0.7283168  0.64638279 0.58232877]]
[[1. 1.]
 [1. 1.]]


## Array
<hr style="height:2px;border-width:0;color:black;background-color:black">

### Array Properties

|Syntax|Description|Documentation|
|:-------------|:-------------|:-----------|
|`array.shape`|Dimensions (Rows,Columns)|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)|
|`len(array)`|Length of Array|[link](https://docs.python.org/3.5/library/functions.html#len)|
|`array.ndim`|Number of Array Dimensions|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html)|
|`array.size`|Number of Array Elements|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html)|
|`array.dtype`|Data Type|[link](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)|
|`array.astype(type)`|Converts to Data Type|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)|
|`type(array)`|Type of Array|[link](https://docs.scipy.org/doc/numpy/user/basics.types.html)|

In [31]:
array = np.ones((2,4))
print(array.shape)
print(len(array))
print(array.ndim)
print(array.dtype)
print(array.astype(int))
print(type(array))

(2, 4)
2
2
float64
[[1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>


### Combining Arrays <a name="comb"></a>
|Operator|Description|Documentation|
|:---------|:-------|:---------|
|`np.concatenate((a,b),axis=0)`|Concatenates 2 arrays, adds to end|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)|
|`np.vstack((a,b))`|Stack array row-wise|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)|
|`np.hstack((a,b))`|Stack array column wise|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)|


In [40]:
a = np.ones((2,4))
b = np.zeros((2,4))
print(np.concatenate((a,b),axis=0))
c = np.ones((1,4))
print(np.vstack((c,b)))
b = np.zeros((2,3))
print(np.hstack((a,b)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]]


### Splitting Arrays <a name="split"></a>
|Operator|Description|Documentation|
|:---------|:-------|:------|
|`numpy.split()`||[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html)|
|`np.array_split(array, 3)`|Split an array in sub-arrays of (nearly) identical size|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_split.html#numpy.array_split)|
|`numpy.hsplit(array, 3)`|Split the array horizontally at 3rd index|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html#numpy.hsplit)|


In [47]:
large_array = np.arange(16).reshape((2,8))
print(np.split(large_array, 2))
print(np.array_split(large_array, 4))
print(np.hsplit(large_array,4))

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]]), array([], shape=(0, 8), dtype=int64), array([], shape=(0, 8), dtype=int64)]
[array([[0, 1],
       [8, 9]]), array([[ 2,  3],
       [10, 11]]), array([[ 4,  5],
       [12, 13]]), array([[ 6,  7],
       [14, 15]])]


### Shaping Arrays <a name="shape"></a>
##### TODO
|Operator|Description|Documentation|
|:---------|:-------|:------|
|`other = ndarray.flatten()`|Flattens a 2d array to 1d|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html)|
|numpy.flip()|Flips order of elements in 1D array||
|np.ndarray[::-1]|Same as above||
|ndarray.reshape|||
|np.squeeze(ndarray)|||
|expand_dims|||

In [83]:
dim_array = np.arange(16).reshape(2,2,4)
print(dim_array.flatten())
print(np.flip(dim_array.flatten()))
print(dim_array.flatten()[::-1])
print(dim_array.reshape(2,-1))
print(str(dim_array.shape) + " || " + str(np.squeeze(dim_array.reshape(4,2,2,1),axis=3).shape))
print(str(dim_array.shape) + " || " + str(np.expand_dims(dim_array,axis=3).shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(2, 2, 4) || (4, 2, 2)
(2, 2, 4) || (2, 2, 4, 1)


### Misc <a name="misc"></a>
|Operator|Description|Documentation|
|:--------|:--------|:--------|
|`other = ndarray.flatten()`|Flattens a 2d array to 1d|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html)|
|`array = np.transpose(other)`</br> `array.T` |Transpose array|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)|
|`inverse = np.linalg.inv(matrix)`|Inverse of a given matrix|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) |
</br>

In [96]:
other = np.array([[10, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(np.transpose(other))
print(np.linalg.inv(other))

[[10  4  7]
 [ 2  5  8]
 [ 3  6  9]]
[[ 0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -2.55555556  1.77777778]
 [ 0.11111111  2.44444444 -1.55555556]]


## Mathematics <a name="maths"></a>

### Operations <a name="ops"></a>
| Operator | Description     |Documentation|
| :------------- | :------------- |:---------|
|`np.add(x,y)`<br/>`x + y`|Addition|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html)|
|`np.substract(x,y)`<br/>`x - y`|Subtraction|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.subtract.html#numpy.subtract)|
|`np.divide(x,y)`<br/>`x / y`|Division|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html#numpy.divide)|
|`np.multiply(x,y)`<br/>`x @ y`|Multiplication|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html#numpy.multiply)|
|`np.sqrt(x)`|Square Root|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html#numpy.sqrt)|
|`np.sin(x)`|Element-wise sine|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html#numpy.sin)|
|`np.cos(x)`|Element-wise cosine|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html#numpy.cos)|
|`np.log(x)`|Element-wise natural log|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html#numpy.log)|
|`np.dot(x,y)`|Dot product|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)|
|`np.roots([1,0,-4])`|Roots of a given polynomial coefficients|[link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roots.html)|
